global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi-backend"
    static_configs:
      - targets: ["practicas-calculadora-1:8000"]
      # - metrics_path: /metrics -> automáticamente es de metrics