name: Build and Push Frontend Docker image

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Necesaria para subir a GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tags
        id: vars
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
            echo "PUSH_LATEST=true" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
            echo "PUSH_LATEST=false" >> $GITHUB_ENV
          fi

      - name: Build Docker image with tag
        run: |
          docker build -t ghcr.io/${{ github.repository }}-frontend:${{ env.TAG }} ./frontend

      - name: Tag as latest (if tagged release)
        if: env.PUSH_LATEST == 'true'
        run: |
          docker tag ghcr.io/${{ github.repository }}-frontend:${{ env.TAG }} ghcr.io/${{ github.repository }}-frontend:latest

      - name: Push image with main tag
        run: |
          docker push ghcr.io/${{ github.repository }}-frontend:${{ env.TAG }}

      - name: Push latest (if tagged release)
        if: env.PUSH_LATEST == 'true'
        run: |
          docker push ghcr.io/${{ github.repository }}-frontend:latest